/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: int32
         * @example 1
         */
        Id: number;
        /**
         * Format: url
         * @example https://example.com/...
         */
        UrlType: string;
        User: {
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
            teamId: string;
            image: components["schemas"]["UrlType"] | null;
            description: string;
            nickname: string;
            id: components["schemas"]["Id"];
        };
        UserDetail: components["schemas"]["User"] & {
            mostFavoriteCategory: {
                name: string;
                id: components["schemas"]["Id"];
            } | null;
            /** Format: double */
            averageRating: number;
            /** Format: double */
            reviewCount: number;
            /** Format: double */
            followeesCount: number;
            /** Format: double */
            followersCount: number;
            isFollowing: boolean;
        };
        /** @example 닉네임 */
        Nickname: string;
        UpdateUserRequestBody: {
            /** @example 안녕하세요 */
            description?: string;
            nickname?: components["schemas"]["Nickname"];
            image?: components["schemas"]["UrlType"];
        };
        UserRanking: components["schemas"]["User"] & {
            /** Format: double */
            reviewCount: number;
            /** Format: double */
            followersCount: number;
        };
        ProductListType: {
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
            writerId: components["schemas"]["Id"];
            categoryId: components["schemas"]["Id"];
            /** Format: double */
            favoriteCount: number;
            /** Format: double */
            reviewCount: number;
            /** Format: double */
            rating: number;
            image: components["schemas"]["UrlType"];
            name: string;
            id: components["schemas"]["Id"];
        };
        CursorBasedPaginationResponse_ProductListType_: {
            /** Format: double */
            nextCursor: number | null;
            list: components["schemas"]["ProductListType"][];
        };
        "CursorBasedPaginationResponse__id-number--followee-User__": {
            /** Format: double */
            nextCursor: number | null;
            list: {
                followee: components["schemas"]["User"];
                /** Format: double */
                id: number;
            }[];
        };
        "CursorBasedPaginationResponse__id-number--follower-User__": {
            /** Format: double */
            nextCursor: number | null;
            list: {
                follower: components["schemas"]["User"];
                /** Format: double */
                id: number;
            }[];
        };
        Review: {
            user: {
                image: components["schemas"]["UrlType"] | null;
                nickname: string;
                id: components["schemas"]["Id"];
            };
            reviewImages: {
                source: components["schemas"]["UrlType"];
                id: components["schemas"]["Id"];
            }[];
            productId: components["schemas"]["Id"];
            userId: components["schemas"]["Id"];
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
            isLiked: boolean;
            /** Format: double */
            likeCount: number;
            content: string;
            /** Format: double */
            rating: number;
            id: components["schemas"]["Id"];
        };
        /** Format: float */
        Rating: number;
        ReviewContent: string;
        CreateReviewRequestBody: {
            productId: components["schemas"]["Id"];
            /** @description 이미지 URL 입니다. 최대 3개까지 가능합니다. */
            images?: components["schemas"]["UrlType"][];
            content: components["schemas"]["ReviewContent"];
            rating: components["schemas"]["Rating"];
        };
        UpdateReviewRequestBody: {
            /**
             * @description 기존 이미지를 유지하려면 id를, 새로운 이미지를 추가하려면 source를 넣어주세요. <br />
             *     요청에 포함되지 않는 기존 이미지는 삭제됩니다.
             */
            images?: ({
                id: components["schemas"]["Id"];
            } | {
                source: components["schemas"]["UrlType"];
            })[];
            content?: components["schemas"]["ReviewContent"];
            rating?: components["schemas"]["Rating"];
        };
        SearchProductResponse: components["schemas"]["CursorBasedPaginationResponse_ProductListType_"];
        ProductDetailType: components["schemas"]["ProductListType"] & {
            /** @description 동일 카테고리 지표 */
            categoryMetric: {
                /** Format: double */
                reviewCount: number;
                /** Format: double */
                favoriteCount: number;
                /** Format: double */
                rating: number;
            };
            category: {
                name: string;
                id: components["schemas"]["Id"];
            };
            isFavorite: boolean;
            description: string;
        };
        /**
         * @description 상품 이름
         * @example 상품 이름
         */
        ProductName: string;
        /**
         * @description 상품 설명
         * @example 상품 설명, 최소 10자 이상, 최대 500자 이하
         */
        ProductDescription: string;
        CreateProductRequestBody: {
            categoryId: components["schemas"]["Id"];
            image: components["schemas"]["UrlType"];
            description: components["schemas"]["ProductDescription"];
            name: components["schemas"]["ProductName"];
        };
        UpdateProductRequestBody: {
            categoryId: components["schemas"]["Id"];
            image: components["schemas"]["UrlType"];
            description: components["schemas"]["ProductDescription"];
            name: components["schemas"]["ProductName"];
        };
        CursorBasedPaginationResponse_Review_: {
            /** Format: double */
            nextCursor: number | null;
            list: components["schemas"]["Review"][];
        };
        ListReviewResponse: components["schemas"]["CursorBasedPaginationResponse_Review_"];
        OauthApp: {
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            appKey: string;
            provider: string;
            teamId: string;
            id: components["schemas"]["Id"];
        };
        /** @enum {string} */
        OauthProvider: "google" | "kakao";
        UpsertOauthAppRequestBody: {
            /**
             * @description 간편 로그인을 위한 인증 키 입니다.
             *     Google 의 경우에는 "클라이언트 id" 입니다.
             *     Kakao 의 경우에는 "REST API 키" 입니다.
             *     실습을 위해 발급받은 키를 등록해주세요. 실제 서비스에서 사용 하는 키는 등록하시면 안됩니다.
             */
            appKey: string;
            provider: components["schemas"]["OauthProvider"];
        };
        FollowRequestBody: {
            /** @description 팔로우할 유저의 id */
            userId: components["schemas"]["Id"];
        };
        Category: {
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            createdAt: string;
            name: string;
            id: components["schemas"]["Id"];
        };
        /**
         * Format: email
         * @example example@email.com
         */
        Email: string;
        SignUpResponse: {
            accessToken: string;
            user: components["schemas"]["User"] & {
                email: components["schemas"]["Email"];
            };
        };
        /** @example password */
        Password: string;
        SignUpRequestBody: {
            passwordConfirmation: components["schemas"]["Password"];
            password: components["schemas"]["Password"];
            nickname: components["schemas"]["Nickname"];
            email: components["schemas"]["Email"];
        };
        SignInResponse: {
            accessToken: string;
            user: components["schemas"]["User"] & {
                email: components["schemas"]["Email"];
            };
        };
        SignInRequestBody: {
            password: components["schemas"]["Password"];
            email: components["schemas"]["Email"];
        };
        /**
         * @description 간편 로그인 과정을 통해 발급받은 토큰입니다.<br />
         *     Google 의 경우에는 <b>Google Id 토큰</b>(JWT) 입니다.<br/>
         *     Kakao 의 경우에는 <b>인가 코드</b> 입니다.
         */
        OauthToken: string;
        SignInWithOauthRequestBody: {
            /**
             * @description Kakao 의 경우에는 필수입니다.<br/>
             *     인가 코드를 얻을 때 사용하였던 redirect_uri 값을 그대로 사용합니다.
             * @example http://localhost:3000/oauth/kakao
             */
            redirectUri?: string;
            token: components["schemas"]["OauthToken"];
        };
        SignUpWithOauthRequestBody: {
            nickname: components["schemas"]["Nickname"];
        } & components["schemas"]["SignInWithOauthRequestBody"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
